server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

clusterLocation: "localhost"
clusterPort: 5555
clusterRPCPort: 8080
